spring.application.name=esp32ota
spring.datasource.url=jdbc:postgresql://localhost:5432/esp32ota
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8083
springdoc.swagger-ui.enabled=true